---
title: "Playing with PCAs"
output: 
  github_document:
  html_preview: true
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}
source("2-code/0-packages.R")
library(ggbiplot)

pal_transect = rev(soilpalettes::soil_palette("redox2", 4))
theme_set(theme_kp())
```

```{r}
targets::tar_load_everything()
```

```{r}
make_data_subset = function(data_combined){
  
 # data_combined_subset = 
    data_combined %>% 
    filter(!transect %in% "wte") %>% 
    #filter(!grepl("Bromide|Fluoride|Nitrate|Calcium|Magnesium|Potassium|Sodium|Phosphate|Ammonia", name, ignore.case = TRUE)) %>% 
    force()
}
make_data_wide = function(data_combined_subset, sample_key){
  
  #data_combined_wide = 
    data_combined_subset %>% 
    dplyr::select(sample_label, analysis, name, value) %>% 
    separate(name, sep = "_", into = "variable", remove = F) %>% 
    #mutate(name = paste0(variable, " (", analysis, ")")) %>% 
    dplyr::select(sample_label, variable, value) %>% 
    pivot_wider(names_from = "variable") %>% 
    left_join(sample_key) %>% 
    filter(!grepl("016", sample_label)) %>% # this one sample is very weird
    force()
  
}

```



```{r, eval=TRUE}

data_combined_subset = make_data_subset(data_combined) # %>% filter(!analysis %in% "LOI")
data_combined_wide_NO_DIC = make_data_wide(data_combined_subset %>% 
                                             filter(!grepl("dic", name, ignore.case = TRUE)),
                                           sample_key)
```


```{r}
## Set df for PCA

data_combined_wide = make_data_wide(data_combined_subset, sample_key)
data_wide_PCA = 
  data_combined_wide %>% 
  dplyr::select(-c("dic", "gwc", "percentOM")) %>% 
  rename(CEC = cec,
         NH4N = nh4n,
         NO3N = no3n,
         P = mehlichp,
         WEOC = npoc)

```


```{r}
fit_pca_function = function(dat){
  
  dat %>% 
    drop_na()
  
  num = 
    dat %>%       
    dplyr::select(where(is.numeric)) %>%
    dplyr::mutate(row = row_number()) %>% 
    drop_na()
  
  num_row_numbers = num %>% dplyr::select(row)
  
  grp = 
    dat %>% 
    dplyr::select(where(is.character)) %>% 
    dplyr::mutate(row = row_number()) %>% 
    right_join(num_row_numbers)
  
  
  num = num %>% dplyr::select(-row)
  pca_int = prcomp(num, scale. = T)
  
  list(num = num,
       grp = grp,
       pca_int = pca_int)
}

```


--- 

## OVERALL

```{r}
## PCA input files ----
pca_overall = fit_pca_function(data_wide_PCA) 
pca_overall_wle = fit_pca_function(dat = data_wide_PCA %>% filter(region == "WLE"))
pca_overall_cb = fit_pca_function(data_wide_PCA %>% filter(region == "CB"))
```

```{r}
## PCA plots overall ----
#gg_pca_overall = 
  ggbiplot(pca_overall$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall$grp$region), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(#shape = pca_overall$grp$transect,
               color = groups))+ 
  scale_color_manual(values = c("#16879C", "#BB281E" ))+
  #scale_shape_manual(values = c(21, 19))+
  #scale_shape_manual(values = c(21, 21, 19), name = "", guide = "none")+
  # xlim(-4,20)+
  # ylim(-8,8)+
  labs(shape="",
       title = "Overall PCA, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL


  ggbiplot(pca_overall$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall$grp$region,
               color = pca_overall$grp$transect))+ 
 # scale_color_manual(values = c("#16879C", "#BB281E" ))+
  scale_shape_manual(values = c(21, 19))+
  #scale_shape_manual(values = c(21, 21, 19), name = "", guide = "none")+
  # xlim(-4,20)+
  # ylim(-8,8)+
  labs(shape="",
       title = "Overall PCA, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

```


### regions separated - colored by transect

```{r, fig.width=10, fig.height=6}
gg_pca_wle = 
  ggbiplot(pca_overall_wle$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_wle$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 1) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_wle$grp$site,
                 color = groups))+ 
  scale_color_manual(breaks = c("upland", "transition", "wte", "wc"), 
                     values = pal_transect)+
  #scale_shape_manual(values = c(21, 19))+
  #scale_shape_manual(values = c(21, 21, 19), name = "", guide = "none")+
  xlim(-6,6)+
  ylim(-4.5,4.5)+
  labs(shape="",
       title = "PCA: WLE",
       subtitle = "surface horizons")+
  theme_kp()+
  theme(legend.position = "top", legend.box = "vertical")+
  NULL

gg_pca_cb = 
  ggbiplot(pca_overall_cb$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_cb$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_cb$grp$site,
                 color = groups))+ 
  scale_color_manual(breaks = c("upland", "transition", "wte", "wc"), 
                     values = pal_transect)+
  #scale_shape_manual(values = c(21, 19))+
  #scale_shape_manual(values = c(21, 21, 19), name = "", guide = "none")+
  xlim(-5.5,7.5)+
  ylim(-5,5)+
  labs(shape="",
       title = "PCA: CB",
       subtitle = "surface horizons")+
  theme_kp()+
  theme(legend.position = "top", legend.box = "vertical")+
  NULL

#  library(patchwork)
#  gg_pca_regions = gg_pca_wle + gg_pca_cb
gg_pca_regions = cowplot::plot_grid(gg_pca_wle , gg_pca_cb)
gg_pca_regions

```

### regions separated - colored by site

```{r, fig.width=10, fig.height=6}
gg_pca_wle = 
  ggbiplot(pca_overall_wle$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_wle$grp$site), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_wle$grp$transect,
                 color = groups))+ 
  xlim(-6,6)+
  ylim(-4.5,4.5)+
  labs(shape="",
       title = "PCA: WLE",
       subtitle = "surface horizons")+
  theme_kp()+
  theme(legend.position = "top", legend.box = "vertical")+
  NULL

gg_pca_cb = 
  ggbiplot(pca_overall_cb$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_cb$grp$site), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_cb$grp$transect,
                 color = groups))+ 
  xlim(-5.5,7.5)+
  ylim(-5,5)+
  labs(shape="",
       title = "PCA: CB",
       subtitle = "surface horizons")+
  theme_kp()+
  theme(legend.position = "top", legend.box = "vertical")+
  NULL

#  library(patchwork)
#  gg_pca_regions = gg_pca_wle + gg_pca_cb
gg_pca_regions = cowplot::plot_grid(gg_pca_wle , gg_pca_cb)
gg_pca_regions

```

---

## BY TRANSECT

```{r}
# BY TRANSECT ----

pca_overall_upland = fit_pca_function(data_wide_PCA %>% filter(transect == "upland"))
pca_overall_transition = fit_pca_function(data_wide_PCA %>% filter(transect == "transition"))
pca_overall_wetland = fit_pca_function(data_wide_PCA %>% filter(transect == "wc"))


gg_overall_upland = 
  ggbiplot(pca_overall_upland$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_upland$grp$region), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_upland$grp$site,
                 color = groups))+ 
  scale_color_manual(values = c("#16879C", "#BB281E" ))+
  labs(shape="",
       title = "PCA upland, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_overall_transition = 
  ggbiplot(pca_overall_transition$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_transition$grp$region), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_transition$grp$site,
                 color = groups))+ 
  scale_color_manual(values = c("#16879C", "#BB281E" ))+
  labs(shape="",
       title = "PCA transition, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_overall_wetland = 
  ggbiplot(pca_overall_wetland$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_overall_wetland$grp$region), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_overall_wetland$grp$site,
                 color = groups))+ 
  scale_color_manual(values = c("#16879C", "#BB281E" ))+
  labs(shape="",
       title = "PCA wetland, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL


gg_overall_upland
gg_overall_transition
gg_overall_wetland


#

```

--- 

## BY TRANSECT + REGION

```{r, fig.width=10, fig.height=6}
# BY TRANSECT + REGION ----

pca_upland_wle = fit_pca_function(data_wide_PCA %>% filter(transect == "upland" & region == "WLE"))
pca_upland_cb = fit_pca_function(data_wide_PCA %>% filter(transect == "upland" & region == "CB"))

gg_upland_wle = 
  ggbiplot(pca_upland_wle$pca_int, obs.scale = 1, var.scale = 1,
         groups = as.character(pca_upland_wle$grp$site), 
         ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(
                 color = groups))+ 
  labs(shape="",
       title = "PCA upland, WLE",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_upland_cb = 
  ggbiplot(pca_upland_cb$pca_int, obs.scale = 1, var.scale = 1,
         groups = as.character(pca_upland_cb$grp$site), 
         ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(
                 color = groups))+ 
  labs(shape="",
       title = "PCA upland, CB",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL


cowplot::plot_grid(gg_upland_wle , gg_upland_cb)

```


```{r, fig.width=10, fig.height=6}

pca_transition_wle = fit_pca_function(data_wide_PCA %>% filter(transect == "transition" & region == "WLE"))
pca_transition_cb = fit_pca_function(data_wide_PCA %>% filter(transect == "transition" & region == "CB"))

gg_transition_wle = 
  ggbiplot(pca_transition_wle$pca_int, obs.scale = 1, var.scale = 1,
         groups = as.character(pca_transition_wle$grp$site), 
         ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(
                 color = groups))+ 
  labs(shape="",
       title = "PCA transition, WLE",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_transition_cb = 
  ggbiplot(pca_transition_cb$pca_int, obs.scale = 1, var.scale = 1,
         groups = as.character(pca_transition_cb$grp$site), 
         ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(
                 color = groups))+ 
  labs(
       title = "PCA transition, CB",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL


cowplot::plot_grid(gg_transition_wle , gg_transition_cb)


```


```{r, fig.width=10, fig.height=6}

pca_wetland_wle = fit_pca_function(data_wide_PCA %>% filter(transect == "wc" & region == "WLE"))
pca_wetland_cb = fit_pca_function(data_wide_PCA %>% filter(transect == "wc" & region == "CB"))

gg_wetland_wle = 
  ggbiplot(pca_wetland_wle$pca_int, obs.scale = 1, var.scale = 1,
         groups = as.character(pca_wetland_wle$grp$site), 
         ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(
                 color = groups))+ 
  labs(
       title = "PCA wetland, WLE",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_wetland_cb = 
  ggbiplot(pca_wetland_cb$pca_int, obs.scale = 1, var.scale = 1,
         groups = as.character(pca_wetland_cb$grp$site), 
         ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(
                 color = groups))+ 
  labs(
       title = "PCA wetland, CB",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

cowplot::plot_grid(gg_wetland_wle , gg_wetland_cb)

```

## BY SITE
```{r}

pca_owc = fit_pca_function(data_wide_PCA %>% filter(site == "OWC")) 
pca_ptr = fit_pca_function(data_wide_PCA %>% filter(site == "PTR")) 
pca_crc = fit_pca_function(data_wide_PCA %>% filter(site == "CRC")) 
pca_gcw = fit_pca_function(data_wide_PCA %>% filter(site == "GCW")) 
pca_msm = fit_pca_function(data_wide_PCA %>% filter(site == "MSM")) 
pca_gwi = fit_pca_function(data_wide_PCA %>% filter(site == "GWI")) 

gg_pca_owc = ggbiplot(pca_owc$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_owc$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(color = groups))+ 
  labs(shape="", title = "PCA OWC", subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_pca_ptr = ggbiplot(pca_ptr$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_ptr$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(color = groups))+ 
  labs(shape="", title = "PCA PTR", subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_pca_crc = ggbiplot(pca_crc$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_crc$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(color = groups))+ 
  labs(shape="", title = "PCA CRC", subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_pca_gcw = ggbiplot(pca_gcw$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_gcw$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(color = groups))+ 
  labs(shape="", title = "PCA GCW", subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_pca_msm = ggbiplot(pca_msm$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_msm$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(color = groups))+ 
  labs(shape="", title = "PCA MSM", subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

gg_pca_gwi = ggbiplot(pca_gwi$pca_int, obs.scale = 1, var.scale = 1,
           groups = as.character(pca_gwi$grp$transect), 
           ellipse = TRUE, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_point(size=3,stroke=1, alpha = 1,
             aes(color = groups))+ 
  labs(shape="", title = "PCA GWI", subtitle = "Surface horizons only")+
  theme_kp()+
  NULL

library(patchwork)

gg_pca_gcw + gg_pca_msm + gg_pca_gwi +
  plot_layout(guides = "collect")&
  theme(legend.position = "bottom")

gg_pca_owc + gg_pca_ptr + gg_pca_crc +
  plot_layout(guides = "collect")&
  theme(legend.position = "bottom")


```

---

## Plotting PC1 (drivers of variability)

```{r}
get_pc_values = function(dat){
  
  pca = fit_pca_function(dat)
  
  x = pca$pca_int$rotation
  x2 = 
    x %>% 
    as.data.frame() %>% 
    dplyr::select(PC1) %>% 
    arrange(desc(PC1)) %>% 
    rownames_to_column("variable") %>% 
    mutate(variable = fct_reorder(variable, (PC1)))

  x2
}
```

```{r}
do_pca = function(dat){
  
  pca = fit_pca_function(dat)
  
  x = pca$pca_int$rotation %>% as.data.frame() %>% rownames_to_column("variable")

}

x = data_wide_PCA %>% group_by(region, transect) %>% do(do_pca(.))

x %>% 
  ggplot(aes(x = PC1, y = PC2, label = variable))+
  geom_point()+geom_text()+
  facet_grid(transect ~ region)


```


```{r, fig.height=8, fig.width=6}

pc_overall = get_pc_values(data_wide_PCA) %>% mutate(region = "combined")
pc_wle = get_pc_values(data_wide_PCA %>% filter(region == "WLE")) %>% mutate(region = "WLE")
pc_cb = get_pc_values(data_wide_PCA %>% filter(region == "CB")) %>% mutate(region = "CB")

pc_all = 
  bind_rows(pc_overall, pc_wle, pc_cb) %>% 
  mutate(variable = fct_reorder(variable, (PC1)))

pc_all %>% 
  mutate(variable = fct_reorder(variable, (PC1))) %>% 
  filter(region != "combined") %>% 
  ggplot(aes(x = PC1, y = variable, color = region))+
  geom_point(size = 5)+
  scale_colour_manual(values = c("#81C0A7", "#1A421D"))+
  xlim(-0.4, 0.4)+
  geom_vline(xintercept = 0)+
  labs(y = "")+
  theme_kp()

pc_all %>% 
  mutate(variable = fct_reorder(variable, (PC1))) %>% 
  filter(region != "combined") %>% 
  ggplot(aes(x = abs(PC1), y = variable, color = region))+
  geom_point(size = 5)+
  scale_colour_manual(values = c("#81C0A7", "#1A421D"))+
 # xlim(0, 0.4)+
  #geom_vline(xintercept = 0)+
  labs(y = "",
       x = "|PC1|")+
  theme_kp()

```

PC1 loadings by transect
```{r}

pc_transect = 
  data_wide_PCA %>% 
  group_by(transect) %>% 
  do(get_pc_values(.)) %>% 
  mutate(transect = factor(transect, levels = c("upland", "transition", "wc")))


pc_transect %>% 
  mutate(variable = fct_reorder(variable, abs(PC1))) %>% 
  ggplot(aes(x = abs(PC1), y = variable))+
  geom_point(size = 5)+
  scale_colour_manual(values = c("#81C0A7", "#1A421D"))+
 # xlim(0, 0.4)+
  #geom_vline(xintercept = 0)+
  labs(y = "",
       x = "|PC1|")+
  facet_grid(. ~ transect)+
  theme_kp()

```


PC1 loadings by region+transect
```{r}

pc_region_transect = 
  data_wide_PCA %>% 
  group_by(region, transect) %>% 
  do(get_pc_values(.)) %>% 
  mutate(transect = factor(transect, levels = c("upland", "transition", "wc")))

pc_region_transect %>% 
  mutate(variable = fct_reorder(variable, abs(PC1))) %>% 
  ggplot(aes(x = abs(PC1), y = variable, color = region))+
  geom_point(size = 5)+
  scale_colour_manual(values = c("#81C0A7", "#1A421D"))+
 # xlim(0, 0.4)+
  #geom_vline(xintercept = 0)+
  labs(y = "",
       x = "|PC1|")+
  facet_grid(. ~ transect)+
  theme_kp()


pc_region_transect %>% 
  filter(transect != "transition") %>% 
  mutate(variable = fct_reorder(variable, abs(PC1))) %>% 
  ggplot(aes(x = abs(PC1), y = variable, color = transect))+
  geom_point(size = 5)+
  scale_colour_manual(values = c("red", "blue"))+
 # xlim(0, 0.4)+
  #geom_vline(xintercept = 0)+
  labs(y = "",
       x = "|PC1|")+
  facet_grid(. ~ region)+
  theme_kp()+
  geom_vline(xintercept = 0.3, linetype = "dashed")+
  geom_vline(xintercept = 0.1, linetype = "dashed")



```

---

## CLUSTERS

```{r}


library(cluster)
library(factoextra)


df = data_wide_PCA %>% filter(region == "CB") %>%   drop_na() %>% dplyr::select(where(is.numeric))
grp = data_wide_PCA %>% filter(region == "CB")%>% drop_na() %>% dplyr::select(!where(is.numeric))

fviz_nbclust(df, FUN = hcut, method = "wss")
fviz_nbclust(df, FUN = hcut, method = "silhouette")
# three clusters

d <- dist(df, method = "euclidean")
hc1 <- hclust(d, method = "complete" )
plot(hc1, cex = 0.6, hang = -1)
hc5 <- hclust(d, method = "ward.D2" )
sub_grp <- cutree(hc5, k = 3)
table(sub_grp)
plot(hc5, cex = 0.6)
rect.hclust(hc5, k = 3, border = 2:5)

df_cl <- mutate(df, cluster = sub_grp) %>% cbind(grp) %>% mutate(cluster = as.character(cluster))
count(df_cl,cluster)

```

```{r}
library(ggConvexHull)

pca_cluster = fit_pca_function(df_cl) 

ggbiplot::ggbiplot(pca_cluster$pca_int, obs.scale = 1, var.scale = 1,
                   groups = as.character(pca_cluster$grp$cluster), 
                   ellipse = F, circle = FALSE, var.axes = TRUE, alpha = 0) +
  geom_convexhull(aes(group = pca_cluster$grp$cluster,
                      fill = pca_cluster$grp$cluster), alpha = 0.2)+
  geom_point(size=3,stroke=1, alpha = 1,
             aes(shape = pca_cluster$grp$site,
                 color = groups))+ 
  # scale_color_manual(values = c("#16879C", "#BB281E" ))+
  #scale_shape_manual(values = c(21, 19))+
  #scale_shape_manual(values = c(21, 21, 19), name = "", guide = "none")+
  # xlim(-4,20)+
  # ylim(-8,8)+
  labs(fill="cluster",
       color = "cluster",
       shape = "region",
       title = "Overall PCA, both regions",
       subtitle = "Surface horizons only")+
  theme_kp()+
  NULL
  
```

```{r}
df_cl %>%
 # distinct(region, site, transect, cluster) %>% 
  ggplot(aes(y = cluster, x = site))+
  geom_point(aes(color = transect, shape = transect),
             size = 4, stroke = 1,
             position = position_jitterdodge(jitter.width = 0.0, jitter.height = 0.1, 
                                             dodge.width = 0.4))

devtools::install_github("liamgilbey/ggwaffle")
library(ggwaffle)

df_cl %>% 
  ggplot()+
  geom_waffle(aes(x = transect, y = site, fill = cluster))
    

    
```

```{r}
wine.pca <- prcomp(wine[treatments], scale = TRUE)

df.wine.x$groups <- wine.class
wine$groups <- wine.class
feature.centroids <- aggregate(wine[treatments], list(Type = wine$groups), mean)

data(wine)
treatments <- 1:2 #treatments to be considerd for this calculation
wine.pca <- prcomp(wine[treatments], scale. = TRUE)
#calculate the centroids for the feature/treatment space and the pca space
df.wine.x <- as.data.frame(wine.pca$x)
df.wine.x$groups <- wine.class
wine$groups <- wine.class
feature.centroids <- aggregate(wine[treatments], list(Type = wine$groups), mean)



dist(rbind(feature.centroids[feature.centroids$Type == "barolo",][-1],
           feature.centroids[feature.centroids$Type == "grignolino",][-1]), method = "euclidean")


data.pca = prcomp(data_wide_PCA %>% drop_na() %>% dplyr::select(where(is.numeric)))
data.feature.centroids <- aggregate(data_wide_PCA %>% drop_na() %>% dplyr::select(where(is.numeric)), 
                                    list(Type = (data_wide_PCA %>% drop_na())$region), 
                                    mean, na.action = na.pass)

dist(rbind(data.feature.centroids[data.feature.centroids$Type == "CB",][-1],
           data.feature.centroids[data.feature.centroids$Type == "WLE",][-1]), method = "euclidean")


centroid.pca = fit_pca_function(data_wide_PCA)$pca_int
centroid.feature = aggregate(data_wide_PCA)


data.feature.centroids = 
  data_combined_subset %>%
  filter(site == "GWI") %>% 
  group_by(transect, name) %>% 
  dplyr::summarise(mean = mean(value, na.rm = T)) %>% 
  pivot_wider(names_from = "name", values_from = "mean")

dist(rbind(data.feature.centroids[data.feature.centroids$transect == "transition",][-1],
           data.feature.centroids[data.feature.centroids$transect == "wetland",][-1]), method = "euclidean")

dist(rbind(data.feature.centroids[data.feature.centroids$transect == "upland",][-1],
           data.feature.centroids[data.feature.centroids$transect == "wetland",][-1]), method = "euclidean")

dist(rbind(data.feature.centroids[data.feature.centroids$transect == "transition",][-1],
           data.feature.centroids[data.feature.centroids$transect == "upland",][-1]), method = "euclidean")

df = data(iris)
dist.iris<-vegdist(iris[,1:4],method = "bray") #calculate Bray-Curtis dissim
dist.iris

#avg distance to group centroids
permdisp<-betadisper(dist.iris,iris$Species,type="centroid")
permdisp
library(usedist)
dist_between_centroids(dist.iris,1:50, 51:100) #1:50 = group setosa, 51:100 = group versicolor

library(vegan)
TukeyHSD(permdisp)



dat.owc = data_wide_PCA %>% filter(site == "OWC") %>% drop_na() 
dist.owc <- vegdist(dat.owc %>% dplyr::select(where(is.numeric)), 
                    method = "bray") #calculate Bray-Curtis dissim
permdisp.owc <- betadisper(dist.owc, dat.owc$transect, type = "centroid")
TukeyHSD(permdisp.owc)

dat.gcw = data_wide_PCA %>% filter(site == "GCW") %>% drop_na() 
dist.gcw <- vegdist(dat.gcw %>% dplyr::select(where(is.numeric)), 
                    method = "bray") #calculate Bray-Curtis dissim
permdisp.gcw <- betadisper(dist.gcw, dat.gcw$transect, type = "centroid")
TukeyHSD(permdisp.gcw)

dat.gwi = data_wide_PCA %>% filter(site == "GWI") %>% drop_na() 
dist.gwi <- vegdist(dat.gwi %>% dplyr::select(where(is.numeric)), 
                    method = "bray") #calculate Bray-Curtis dissim
permdisp.gwi <- betadisper(dist.gwi, dat.gcw$transect, type = "centroid")
TukeyHSD(permdisp.gwi)



```

```{r}
library(mosaic)
x1 <- c(1,0,0); x2 <- c(1,2,3); y1 <- c(3,4,5); y2 <- rnorm(3)
# projection onto the 1 vector gives the mean vector
mean(y2)            
mosaic::project(y2, 1)
# return the length of the vector, rather than the vector itself
project(y2, 1, type='length')
project(y1 ~ x1 + x2) -> pr; pr

project(x, y, type = "length")

```



---

## CV

```{r}
cv = 
  data_combined %>% 
  group_by(region, site, transect, horizon, analysis, name) %>% 
  dplyr::summarise(cv = 100 * sd(value)/mean(value),
                   sd = sd(value),
                   n = n(),
                   mean = mean(value)) %>% 
  filter(!transect %in% "wte") %>% 
  filter(!(name == "Al_meq100g" & region == "WLE")) %>% 
  filter(name != "gwc_perc")

```

```{r}
(cv %>% 
   filter(!(name == "Al_meq100g" & region == "WLE")) %>% 
  ggplot(aes(x = transect, y = cv))+
  geom_violin(scale = "area", fill = "grey90")+
  geom_jitter(width = 0.1, size = 3, aes(color = site, text = name))+
   geom_boxplot(width = 0.05, outlier.color = NA, fill = "white")+
  facet_wrap(~region)+
   theme_kp())  %>% plotly::ggplotly()


cv %>% 
  ggplot(aes(x = region, y = cv))+
  geom_point(width = 0.1, aes(color = transect), 
             position = position_dodge(width = 0.2))+
  expand_limits(y = 0)+
  scale_y_log10()+
  facet_wrap(~ name, 
             #scales = "free_y"
             )

cv %>% 
  filter(!(name == "Al_meq100g" & region == "WLE")) %>% 
  ggplot(aes(x = name, y = cv))+
  geom_violin()+
  geom_point(width = 0.1, aes(color = region), 
            # position = position_dodge(width = 0.9)
             )+
  expand_limits(y = 0)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_grid(transect ~ .)+
#  scale_y_log10()+
  NULL

cv %>% 
  filter(!(name == "Al_meq100g" & region == "WLE")) %>% 
  ggplot(aes(y = name, x = cv))+
  geom_violin(aes(color = region))+
  geom_point(width = 0.1, aes(color = region), 
             position = position_dodge(width = 0.9)
             )+
  expand_limits(x = 0)+
#  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~transect)+
#  scale_y_log10()+
  NULL

cv %>% 
  ggplot(aes(x = mean, y = cv, color = region))+
  geom_point()+
  facet_wrap(~name, scales = "free_x")



View(data_combined_wide %>% dplyr::select(region, site, transect, horizon, contains(c("dic", "pH"))))
```

```{r}
library(ggwaffle)
cv %>% 
  ggplot(aes(x = transect, y = name, fill = cv))+
  geom_waffle()+
  geom_text(aes(label = round(cv,2)), color = "black")+
  scale_fill_gradientn(trans = "log",
                       colors = PNWColors::pnw_palette("Bay", 12), breaks = c(0, 10, 20, 40, 100, 200))+
  facet_wrap(~region + site)
  
cv[cv == "NaN"] <- NA
cv = v %>% drop_na()

aov(cv ~ transect + region + name, data = cv) %>% summary()


library(nlme)
nlme::lme(cv ~ transect, random = ~1|name, data = cv %>% drop_na() %>% filter(region == "WLE")) %>% anova()
nlme::lme(cv ~ region, random = ~1|transect, data = cv %>% drop_na()) %>% anova()


cv %>% group_by(region, transect) %>% dplyr::summarise(mean_cv = mean(cv, na.rm = T))


a = aov((cv) ~ transect, data = cv %>% filter(region == "CB"))
agricolae::HSD.test(a, "transect") %>% print()

a = aov((cv) ~ transect, data = cv %>% filter(region == "WLE"))
agricolae::HSD.test(a, "transect") %>% print()
```



---

## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>